name: Hello World Actions

on: [push]

jobs:
  hello-World-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello World"
        
      - name: Hello World Again
        run: echo "Hello World Again"