name: Run Python Script
on: [push]
jobs:
  runs-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Inicio
        run: echo "Comienzaaaa!"
      - name: Clona el repositorio
        uses: actions/checkout@v6
      - name: Muestra archivos
        run: ls -al
      - name: definir variable de entorno
        run: echo "USERNAME= ${{ github.actor }}" >> $GITHUB_ENV
      - name: Ejecutar script
        run: python app.py

  runs-javascript-script:
    runs-on: ubuntu-latest
    steps:
      - name: Inicio
        run: echo "Comienzaaaa!"
      - name: Clona el repositorio
        uses: actions/checkout@v6
      - name: Muestra archivos
        run: ls -al
      - name: definir variable de entorno
        run: echo "USERNAME= ${{ github.actor }}" >> $GITHUB_ENV
      - name: Ejecutar script
        run: node app.js